POST http://localhost:3000/api/tasks/add HTTP/1.1
Content-Type: application/json

{
  "title": "Conectada3", 
  "description": "Ojalá esto no explote xd"
}

###

GET http://localhost:3000/api/tasks HTTP/1.1
Content-Type: application/json

###

PUT http://localhost:3000/api/tasks/65fef045cf6554348b404d6c/edit HTTP/1.1
Content-Type: application/json

{
  "title": "Conectada2v2",
  "description": "He sido modificada ;v"
}

###

DELETE http://localhost:3000/api/tasks/65fef6034d189e4b7eb38ff2/delete HTTP/1.1
Content-Type: application/json
