POST http://localhost:3000/api/tasks/add HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDZlZDRiNjYwMjFhZjBkYTY1MTIyMyIsImlhdCI6MTcxMTcyOTk5NSwiZXhwIjoxNzExODE2Mzk1fQ.IR_MTzSxLk6c00zKuzHF7cX-1XM_hlxcVfZqpmI1DHQ

{
  "title": "Tarea 6", 
  "description": "Ojalá esto no explote 3 xd",
  "user": "6606ed4b66021af0da651223"
}

###

GET http://localhost:3000/api/tasks/6606ed4b66021af0da651223 HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDZlZDRiNjYwMjFhZjBkYTY1MTIyMyIsImlhdCI6MTcxMTcyOTk5NSwiZXhwIjoxNzExODE2Mzk1fQ.IR_MTzSxLk6c00zKuzHF7cX-1XM_hlxcVfZqpmI1DHQ

###

PUT http://localhost:3000/api/tasks/6606ed4b66021af0da651223/edit/6606f4d0c1b1514744859aa3 HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDZlZDRiNjYwMjFhZjBkYTY1MTIyMyIsImlhdCI6MTcxMTcyOTk5NSwiZXhwIjoxNzExODE2Mzk1fQ.IR_MTzSxLk6c00zKuzHF7cX-1XM_hlxcVfZqpmI1DHQ

{
  "title": "Conectada2v4",
  "description": "He sido modificada ;v"
}

###

DELETE http://localhost:3000/api/tasks/6606ed4b66021af0da651223/delete/6606f3a5c1b1514744859a9d HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDZlZDRiNjYwMjFhZjBkYTY1MTIyMyIsImlhdCI6MTcxMTcyOTk5NSwiZXhwIjoxNzExODE2Mzk1fQ.IR_MTzSxLk6c00zKuzHF7cX-1XM_hlxcVfZqpmI1DHQ

### 

POST http://localhost:3000/api/auth/signup HTTP/1.1
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "Janedoe@gmail.com", 
  "password": "123123",
  "confirmedPassword": "123123"
}

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDZlZDRiNjYwMjFhZjBkYTY1MTIyMyIsImlhdCI6MTcxMTcyOTk5NSwiZXhwIjoxNzExODE2Mzk1fQ.IR_MTzSxLk6c00zKuzHF7cX-1XM_hlxcVfZqpmI1DHQ

###

POST http://localhost:3000/api/auth/signin HTTP/1.1
Content-Type: application/json
x-access-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MDZlZDRiNjYwMjFhZjBkYTY1MTIyMyIsImlhdCI6MTcxMTcyOTk5NSwiZXhwIjoxNzExODE2Mzk1fQ.IR_MTzSxLk6c00zKuzHF7cX-1XM_hlxcVfZqpmI1DHQ

{
  "email": "Janedoe@gmail.com",
  "password": "123123"
}